  tasks:
    - name: NVim
      init: >
          curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz &&
          sudo rm -rf /opt/nvim && 
          sudo tar -C /opt -xzf nvim-linux64.tar.gz &&
          sudo rm nvim-linux64.tar.gz &&
          echo `export PATH="$PATH:/opt/nvim-linux64/bin"` >> ~/.bashrc &&
          source ~/.bashrc

      command: nvim -v